name: Deploy to EC2

on:
  push:
    branches:
      - main  # or specify the branch you want to trigger deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Add SSH config for Climate-mitigate
        run: |
          echo -e "Host Climate-mitigate\n\tHostName ec2-3-11-89-45.eu-west-2.compute.amazonaws.com\n\tIdentityFile ~/.ssh/deployment_key.pem\n\tUser ubuntu" >> ~/.ssh/config

      - name: Deploy application
        run: |
          ssh Climate-mitigate 'bash -s' << 'EOF'
          cd /path/to/your/application
          # Commands to pull changes, install dependencies, and restart your service
          git pull origin main
          npm install
          pm2 restart your-app-name  # Or replace with your service manager
          EOF
